_target_: src.models.soil_module.SoilLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.conv_net.ConvNet
  data_days_before: ${data.days_before}
  data_days_after: ${data.days_after}
  data_features: ${data.features}
  h_in: 70
  w_in: 140
  kernel_size1: 5
  stride1: 1
  padding1: 2
  conv_out1: 256   
  kernel_size2: 3
  stride2: 1
  padding2: 1
  conv_out2: 128
  kernel_size3: 3
  stride3: 1
  padding3: 1
  conv_out3: 64
  kernel_size4: 3
  stride4: 1
  padding4: 1
  conv_out4: 1

# compile model for faster training with pytorch 2.0
compile: false
